Upgrade the config and use a shared domain
openflighthpc/flight-web-auth-api pull request #3
Opened 2021-06-14 12:39 UTC by WilliamMcCumstie

This PR does two things:

1. Upgrade to use `flight_configuration`, and
2. Use the shared `flight_WEB_SUITE_domain`

2021-06-17 16:25 UTC, benarmston requested changes

2021-06-17 16:25 UTC, benarmston commented on config/boot.rb
> +end
Nice workaround.

2021-06-17 16:25 UTC, benarmston commented on lib/flight.rb
> +        ENV['RACK_ENV'].presence || "production"
Rack applications default to `development`.  IIUC that is done by defaulting `RACK_ENV` to `development`.

If I'm correct about that *mechanism* then `|| "production"` will never be executed.  If I'm not correct, we're going to end up with `Flight.env` differing from the application's default environment.

The `|| "production"` should change to `|| "development"` for rack apps.

2021-06-17 16:25 UTC, benarmston commented on etc/login-api.yaml
> +#>>path<<
I'm not keen on this mechanism.  See my comments on the omnibus builder PR for more details.

2021-06-17 16:25 UTC, benarmston commented on lib/flight_login/configuration.rb
> +    RC = Dotenv.parse(File.join(Flight.root, 'etc/web-suite.rc'))
That's a better way of parsing `.rc` files than I'd thought of.

2021-06-17 16:25 UTC, benarmston commented on lib/flight_login/configuration.rb
> +        default: ->() { RC["flight_WEB_SUITE_domain"] }
This can be simplified to `default: RC["flight_WEB_SUITE_domain"]`.

2021-06-17 16:25 UTC, benarmston commented on lib/flight_login/configuration.rb
> +        raise ConfigError, "The shared_secret_path does not exist! #{shared_secret_path}"
Much nicer!

2021-06-18 15:38 UTC, WilliamMcCumstie commented on config/boot.rb
> +end
:+1:

2021-06-18 15:40 UTC, WilliamMcCumstie commented on lib/flight_login/configuration.rb
> +    RC = Dotenv.parse(File.join(Flight.root, 'etc/web-suite.rc'))
:+1:

2021-06-18 15:40 UTC, WilliamMcCumstie commented on lib/flight_login/configuration.rb
> +        raise ConfigError, "The shared_secret_path does not exist! #{shared_secret_path}"
:+1:

2021-06-18 16:05 UTC, WilliamMcCumstie commented on etc/login-api.yaml
> +#>>path<<
ab05095a45d8d8d1072df583e8023454c87774f3

2021-06-18 16:06 UTC, WilliamMcCumstie commented on lib/flight.rb
> +        ENV['RACK_ENV'].presence || "production"
86e506f911ce671733e3323d1bdb72e59cd2322f

2021-06-18 16:07 UTC, WilliamMcCumstie commented on lib/flight_login/configuration.rb
> +        default: ->() { RC["flight_WEB_SUITE_domain"] }
be6d363d67dc3536a13d3ad8c3f570aa6f7d8743

2021-06-21 13:00 UTC, benarmston commented on lib/flight_login.rb
> +  # TODO: Replace me permanently with the Flight stub
Let's make this change now too.  We may as well port it all the way.

2021-06-24 13:39 UTC, benarmston commented on lib/flight_login.rb
> +  # TODO: Replace me permanently with the Flight stub
Done.

2021-06-24 13:41 UTC, benarmston commented
LGTM.

2021-06-24 14:51 UTC, merged